services:
  metabase:
    image: metabase/metabase:v0.58.7.x
    container_name: metabase
    hostname: metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: Secret123
    volumes:
      - /dev/urandom:/dev/random:ro
    networks:
      - metanet1
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: Secret123
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - metanet1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabaseappdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  metanet1:
    driver: bridge
